### ISSUE TITLE
Group attribute does not result in correct rendering

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil-router#28]
Using the `group` attribute to render not found pages can result in unpredictable behavior.

If you are using the following router configuration:

```tsx
<stencil-router>
    <stencil-route url="/" exact group="root" component="my-home" />
    <stencil-route url="/about" exact group="root" component="my-about" />
    <stencil-route url="/*" exact group="root" component="my-not-found" />
</stencil-router>
```

For the url `/about` you will sometimes get the about page but you will also sometimes get the not-found page.  This is because the route matching is not done in a predictable order.  The first route within the group that successfully matches "wins" so if the not-found route happens to evaluate first then it will be the one that gets rendered.

This was a real bear to track down because it only seems to happen as the application gets larger.  For a simple application the routes happen to be evaluated in the order that they are defined.  Once my application got larger I started to see the behavior where the order was not predictable.  It may be related to timing of other async component loading.

The end result is that you can keep refreshing the page and sometimes get the page you want and sometimes get the not found page.

**Comment by jthoms1** [comment]
I would like to change this to be more explicit of a catch all and use a switch component similar to React-Router. I understand the situation you are explaining and it makes sense.

**Comment by cjorasch** [comment]
That's probably a better fit for the typical use case.

**Comment by isikfsc** [comment]
What about the case you have some routes that have a different layout which do not have the shared elements like tab bars etc. of a base route and have its own for example tab bar or do not have it at all. Think about '/' has a bottom tab bar  and not exact equals true, and so '/about' shares that tab bar, and a '/profile' route that does not share this tab bar. I could not manage to attain this 10 days ago. Maybe things have changed since then.
